version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: http-proxy-middleware
    versions:
    - 1.0.6
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: react-dev-utils
    versions:
    - 11.0.1
    - 11.0.2
    - 11.0.3
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: react-error-overlay
    versions:
    - 6.0.8
  - dependency-name: elliptic
    versions:
    - 6.5.3
